#  RMS Normalization

# Normalization

**Layer Normalization**

In [ ]:
import torch
import torch.nn as nn

class LayerNorm(nn.Module):
    def __init__(self, dim, eps=1e-5):
        super().__init__()

        self.eps = eps

        # Learnable scale (γ)
        self.weight = nn.Parameter(torch.ones(dim))

        # Learnable bias (β)
        self.bias = nn.Parameter(torch.zeros(dim))

    def forward(self, x):

        # Step 1: Compute Mean
        mean = x.mean(dim=-1, keepdim=True)

        # Step 2: Compute Variance
        var = ((x - mean) ** 2).mean(dim=-1, keepdim=True)

        # Step 3: Normalize
        x_hat = (x - mean) / torch.sqrt(var + self.eps)

        # Step 4: Scale and Shift
        return self.weight * x_hat + self.bias


# Example
x = torch.tensor([[3., 4., 5.]])

layer_norm = LayerNorm(3)

print("Input")
print(x)

print("\nLayerNorm Output")
print(layer_norm(x))

Input
tensor([[3., 4., 5.]])

LayerNorm Output
tensor([[-1.2247,  0.0000,  1.2247]], grad_fn=<AddBackward0>)


**RMS Normalization**

In [ ]:
import torch
import torch.nn as nn

class RMSNorm(nn.Module):
    def __init__(self, dim, eps=1e-6):
        super().__init__()

        self.eps = eps

        # Learnable scale (γ)
        self.weight = nn.Parameter(torch.ones(dim))

    def forward(self, x):

        # Step 1: Compute Root Mean Square
        rms = torch.sqrt(torch.mean(x ** 2, dim=-1, keepdim=True) + self.eps)

        # Step 2: Normalize
        x_hat = x / rms

        # Step 3: Scale
        return self.weight * x_hat


# Example
x = torch.tensor([[3., 4., 5.]])

rms_norm = RMSNorm(3)

print("Input")
print(x)

print("\nRMSNorm Output")
print(rms_norm(x))

Input
tensor([[3., 4., 5.]])

RMSNorm Output
tensor([[0.7348, 0.9798, 1.2247]], grad_fn=<MulBackward0>)


**Difference**

In [ ]:
import torch

x = torch.tensor([[3., 4., 5.]])

print("=" * 70)
print("INPUT")
print("=" * 70)
print(x)

#########################################################
# Layer Normalization
#########################################################

print("\n")
print("=" * 70)
print("LAYER NORMALIZATION")
print("=" * 70)

mean = x.mean(dim=-1, keepdim=True)
print("\nStep 1 : Mean")
print(mean)

variance = ((x - mean) ** 2).mean(dim=-1, keepdim=True)
print("\nStep 2 : Variance")
print(variance)

std = torch.sqrt(variance + 1e-5)
print("\nStep 3 : Standard Deviation")
print(std)

layer_norm = (x - mean) / std

print("\nStep 4 : Final LayerNorm Output")
print(layer_norm)

#########################################################
# RMS Normalization
#########################################################

print("\n")
print("=" * 70)
print("RMS NORMALIZATION")
print("=" * 70)

square = x ** 2

print("\nStep 1 : Square")
print(square)

mean_square = square.mean(dim=-1, keepdim=True)

print("\nStep 2 : Mean of Squares")
print(mean_square)

rms = torch.sqrt(mean_square + 1e-6)

print("\nStep 3 : Root Mean Square")
print(rms)

rms_norm = x / rms

print("\nStep 4 : Final RMSNorm Output")
print(rms_norm)

#########################################################
# Comparison
#########################################################

print("\n")
print("=" * 70)
print("COMPARISON")
print("=" * 70)

print(f"""
LayerNorm
---------
✓ Computes Mean
✓ Computes Variance
✓ Computes Standard Deviation
✓ Subtracts Mean
✓ Divides by Std
✓ Learnable Gamma
✓ Learnable Beta

RMSNorm
-------
✗ No Mean
✗ No Variance
✗ No Mean Subtraction
✓ Computes Mean of Squares
✓ Computes RMS
✓ Divides by RMS
✓ Learnable Gamma
✗ No Beta
""")

INPUT
tensor([[3., 4., 5.]])


LAYER NORMALIZATION

Step 1 : Mean
tensor([[4.]])

Step 2 : Variance
tensor([[0.6667]])

Step 3 : Standard Deviation
tensor([[0.8165]])

Step 4 : Final LayerNorm Output
tensor([[-1.2247,  0.0000,  1.2247]])


RMS NORMALIZATION

Step 1 : Square
tensor([[ 9., 16., 25.]])

Step 2 : Mean of Squares
tensor([[16.6667]])

Step 3 : Root Mean Square
tensor([[4.0825]])

Step 4 : Final RMSNorm Output
tensor([[0.7348, 0.9798, 1.2247]])


COMPARISON

LayerNorm
---------
✓ Computes Mean
✓ Computes Variance
✓ Computes Standard Deviation
✓ Subtracts Mean
✓ Divides by Std
✓ Learnable Gamma
✓ Learnable Beta

RMSNorm
-------
✗ No Mean
✗ No Variance
✗ No Mean Subtraction
✓ Computes Mean of Squares
✓ Computes RMS
✓ Divides by RMS
✓ Learnable Gamma
✗ No Beta

